---
Description: "This document is a sample configuration file that contains sample configurations for your spaces app."
app_local_path: apps
dependencies:
  - pyserini
  - faiss-cpu
  - torch
indices: "/Users/mac/Documents/castorini/hf-spacerini/apps/Gradio-Pyserini/lucene-index.msmarco-v1-passage.20221004.252b5e"
packages:
  - openjdk-11-jdk
page_icon: รฐ
space_sdk: streamlit
space_name: Pyserini
title: Pyserini
lang_code: en
